##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  guns配置  ###################
guns:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: true #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

###################  项目启动端口  ###################
server:
  port: 9898

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false


###################  spring配置  ###################
spring:
  redis:
    host: localhost
    port: 6379
    password:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.modular.system.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

---
##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://rm-2ze30r012o24384ge137.mysql.rds.aliyuncs.com:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: guns
    password: guns
    db-name: guns
    filters: log4j,wall,mergeStat

    #flowable数据源和多数据源配置
guns:
  flowable:
    datasource:
      url: jdbc:mysql://rm-2ze30r012o24384ge137.mysql.rds.aliyuncs.com:3306/guns_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: guns
      password: guns
  muti-datasource:
    default-dataSource-name: dataProdSourceGuns #
    url: jdbc:mysql://rm-2ze30r012o24384ge137.mysql.rds.aliyuncs.com:3306/guns_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: guns
    password: guns
  local-bdp-datasource:
    default-dataSource-name: localProdBdpDataSource #
    url: jdbc:mysql://rm-2ze30r012o24384ge137.mysql.rds.aliyuncs.com:3306/kaishustory_pagelog?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: bdp
    password: Kaishu2099@!@
  dev-datasource:
    default-dataSource-name: devProdDataSource #
    url: jdbc:mysql://rm-2ze30r012o24384ge137.mysql.rds.aliyuncs.com:3306/wx-pagelog?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: bdp
    password: Kaishu2099@!@
  prod-datasource:
    default-dataSource-name: read3ProdDataSourceP #添加设备id用数据源，查询线上数据库
    url: jdbc:mysql://rr-2zezf05z111gg83r2740.mysql.rds.aliyuncs.com:3306/kaishustory_users?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: kaishustory
    password: kaishu2099
  prod-logcheck-datasource:
    default-dataSource-name: prodLogchekDataSourceP #读取线上环境的打点
    url: jdbc:mysql://rm-2ze30r012o24384ge137.mysql.rds.aliyuncs.com:3306/kaishustory_pagelog?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: bdp
    password: Kaishu2099@!@
  test-datasource:
    default-dataSource-name: testDataSourceP #
    url: jdbc:mysql://rds0115q7em67d875g0a191.mysql.rds.aliyuncs.com:3306/kaishustory_users?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: kaishustory
    password: kaishu2099
logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: guns.log

#整合的外部应用
out-server:
  tag-server: http://172.17.8.124:9074/
---

  ##########################################################
  ###################  开发环境的profile  ###################
  ##########################################################
spring:
  profiles: dev
  datasource:
#    url: jdbc:mysql://rm-2ze30r012o24384ge137.mysql.rds.aliyuncs.com:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    url: jdbc:mysql://localhost:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useAffectedRows=true
    username: root
    password: hanzhen
#    username: guns
#    password: guns
    db-name: guns
    filters: log4j,wall,mergeStat

  #flowable数据源和多数据源配置
guns:
  flowable:
    datasource:
#      url: jdbc:mysql://rm-2ze30r012o24384ge137.mysql.rds.aliyuncs.com:3306/guns_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      url: jdbc:mysql://localhost:3306/guns_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#      username: guns
#      password: guns
      username: root
      password: hanzhen
  muti-datasource:
    default-dataSource-name: dataSourceGuns #
    url: jdbc:mysql://rm-2ze30r012o24384ge137.mysql.rds.aliyuncs.com:3306/guns_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: guns
    password: guns
  local-bdp-datasource:
    default-dataSource-name: localBdpDataSource #
    url: jdbc:mysql://rm-2ze30r012o24384ge137.mysql.rds.aliyuncs.com:3306/kaishustory_pagelog?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: bdp
    password: Kaishu2099@!@
  dev-datasource:
    default-dataSource-name: devDataSource #
    url: jdbc:mysql://rm-2ze30r012o24384ge137.mysql.rds.aliyuncs.com:3306/wx-pagelog?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: bdp
    password: Kaishu2099@!@
  prod-datasource:
    default-dataSource-name: read3ProdDataSource #
    url: jdbc:mysql://rr-2zezf05z111gg83r2740.mysql.rds.aliyuncs.com:3306/kaishustory_users?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: kaishustory
    password: kaishu2099
  prod-logcheck-datasource:
    default-dataSource-name: prodLogchekDataSource #读取线上环境的打点
    url: jdbc:mysql://rm-2ze30r012o24384ge137.mysql.rds.aliyuncs.com:3306/kaishustory_pagelog?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: bdp
    password: Kaishu2099@!@
  test-datasource:
    default-dataSource-name: testDataSource #
    url: jdbc:mysql://rds0115q7em67d875g0a191.mysql.rds.aliyuncs.com:3306/kaishustory_users?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: kaishustory
    password: kaishu2099
logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: guns.log

#整合的外部应用地址
out-server:
  tag-server: http://172.17.8.124:9074/
